---
collections:
  - name : "https://galaxy.ansible.com/download/ansible-posix-1.5.4.tar.gz"
  - name : "https://galaxy.ansible.com/download/imp1sh-ansible_managemynetwork-0.4.6.tar.gz"
  - name : "/var/www/html/collections/fedora-linux_system_roles-1.89.0.tar.gz"

