---
- name: FTP 서버 구성
  hosts: test
  tasks:
    #################################
    # 0) 준비 사항
    # * files/vsftpd.conf
    #             -> anonymous disable
    # * files/{user_list, ftpusers}
    #             -> root 사용자 허용
    # 1) 패키지 설치 - vsftpd, firewalld
    # 2) 서비스 설정 - 파일배포
    #   * /etc/vsftpd.conf
    #   * /etc/
    # 3) 서비스 기동 - vsftpd
    # 4) 방화벽 등록 - ftp
    ##############################
    - name: 패키지 설치 - vsftpd, firewalld
      ansible.builtin.dnf:
        name:
          - vsftpd
          - firewalld
          - ftp
        state: present

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: /etc/vsftpd/
        owner: root
        group: root
        mode: '0600'
      loop:
        - user_list
        - ftpusers

    - name: 설정 파일 배포 - /etc/vsftpd/vsftpd.conf
      ansible.builtin.template:
          src: files/vsftpd.conf
          dest: /etc/vsftpd/
          owner: root
          group: root
          mode: '0600'
      vars:
        anonymous_on: "no"
      notify: restart_ftpd

    - name: 서비스 기동 
      ansible.builtin.systemd:
        state: started
        name: "{{ item }}"
        enabled: true
      loop:
        - firewalld
        - vsftpd

    - name: 방화벽 포트 등록
      ansible.posix.firewalld:
        service: ftp
        permanent: true
        state: enabled
        immediate: true
  handlers:
    - name: restart_ftpd
      ansible.builtin.systemd:
        state: restarted
        name: vsftpd
