---
- name: 3
  hosts: webservers
  gather_facts: true     
  tasks:
  #######################################################
  # 에러메세지 점검:
  # * sdb 디스크가 없으면 => 'The device does not exist'
  # * 파티션이 800MiB 보다 작으면 => 'Size not Enough'
  # LVM 작업
  # * 파티션 작업
  # * LVM 작업
  #     - VG 작업
  #     - LV 작업
  # * 파일시스템 작업
  # * 마운트 작업(/etc/fstab)
  #######################################################
    - name: 에러메세지 출력
      ansible.builtin.fail:
        msg: 'The device does not exist'
      when: ansible_devices.sdb is not defined


    - name: 에러메세지 출력
      community.general.parted:
  # parted /dev/sdb mkpart primary 1MiB 100%
  # parted /dev/sdb set 1 lvm on

        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 1MiB
        part_end: 100%
















    # - name: 에러메세지 출력
    #   ansible.builtin.debug:
    #     msg: 'The device does not exist'
    #   when: ansible_default_ipv4.gateway is defined