---
- name: fedora.linux_system_roles.storage 사용하여 작업하기
  hosts: dev
  roles:
    - name: fedora.linux_system_roles.storage
      storage_pools:
        - name: research 
          type: lvm
          disks:
            - /dev/sdb
          volumes:
            - name: data
              size: 500m
              mount_point: "/mnt/research"
              fs_type: ext4
              state: present
              
