---
- name: 0) 패키지 설치 1
  hosts: dev,test,prod
  gather_facts: false
  tasks:
    - name : 패키지 설치 - p, m
      ansible.builtin.dnf:
        name:
          - php
          - mariadb
        state: present


- name: 0) 패키지 설치 1
  hosts: dev
  gather_facts: false
  tasks:
    - name : 패키지 설치 - iotop, Development Tools
      ansible.builtin.dnf:
        name:
          - iotop
          - '@Development Tools'
        state: present
